#!/bin/sh
set -e
if [ "$1" = "remove" ] || [ "$1" = "purge" ]; then
    rm -f /usr/bin/raw_hailo_inference
fi
if [ "$1" = "purge" ]; then
    rm -rf /etc/picam-hailo
    rm -rf /var/lib/picam-hailo
fi
